### ISSUE TITLE
I need to add some data to this application

### ISSUE THREAD

**Issue by dmenuz** [UGS-GIO/wetlands#13]
I am working on getting new data ready to be submitted to the application based on the project I described on January 7, 2021. Below is a brief description of project steps. I will respond to this message when the data are available.

1) Add new layers to the database; there will be 5 layers in all (though one is the same as the river subbasins layer). EAch layer will have a large number of fields. Layers will be in a placed in a new group within the Legend (Landscape Data).
2) I will need to determine how to best visualize each layer. Likely each layer will be symbolized based on a different. I may want to visualize each layer more than once to be able to symbolize on more than one field OR if possible, create a function to switch how layers are visualized.
3) Format pop-ups and tool tips for each layer
4) Add option to view graphs for some layers.
5) Add new text to the Database Contents section

**Comment by marthajensen** [comment]
@dmenuz I think this data might be covered by a newer issue --  https://github.com/UGS-GIO/wetlands/issues/18

so I'm going to close this one.
