### ISSUE TITLE
Suggest static text edit

### ISSUE THREAD

**Issue by wetlandsDiane** [UGS-GIO/wetlands#21]
What panel are you suggesting changes for?
Database contents, and then under Wetland and Riparian Mapping, and then under Wetland and riparian polygons, wetland outlines, and riverine features

Are you suggesting an edit to text that already exists or proposing additional text?
Minor edit to existing text

What do you suggest the text says?
Sentence that begins: Wetland data are derived from the U.S. Fish and Wildlife Service’s National Wetlands Inventory(NWI) and are up-to-date as of" should have the date updated to June 18, 2021.

Stephanie, presumably you don't need to review this, but I don't know how to untag you from the issue.

**Comment by marshallrobinson** [comment]
Thanks @wetlandsDiane, @jjhi11 will you please update this date?
