### ISSUE TITLE
Wetland Conditions (legend titles)

### ISSUE THREAD

**Issue by marshallrobinson** [UGS-GIO/wetlands#41]
### What happened?

Lower-case legend titles appear.

### What did you expect to happen?

I suggest that the legend titles get removed.

### Browser Version

Chrome (newest release)

**Comment by jjhi11** [comment]
These are need in some cases (Landscape Data). To remove programmatically would be tough at this point. May be possible to change them in the feature layers more easily.

**Comment by marthajensen** [comment]
Data has been republished - this issue should be fixed in the  new service

![image](https://user-images.githubusercontent.com/11522897/157505944-5503a906-0c53-483f-a252-6e79b21c2379.png)

**Comment by marshallrobinson** [comment]
I'm not sure I follow. It doesn't look like the new service did what I was expecting @marthajensen.

That's okay if they're not easily removed w/code, I kinda assumed that it would be taken care of on the service like Martha was thinking.

![image](https://user-images.githubusercontent.com/5225390/157558338-0deed1aa-d38e-45e7-b1eb-adfab659fc17.png)
