### ISSUE TITLE
Study Results popup fields not consistent

### ISSUE THREAD

**Issue by marshallrobinson** [UGS-GIO/wetlands#43]
### What happened?

Some fields in the "Study Results" layer popups are missing.

e.g. 'Stressors Absent' is missing from the Jordan URAP feature

### What did you expect to happen?

In the study results pop-up, can you make the same fields show up in each pop-up, even if the field value is 0?

### Browser Version

Chrome (newest release)

**Comment by marshallrobinson** [comment]
Porting this issue over from a Google Doc conversation (summarized below):

@jjhi11 says that 0-values will show up in the popup while null values will not.
@wetlandsDiane says she checked the service and finds 0-values in the fields that aren't showing up.

**Comment by jjhi11** [comment]
@marshallrobinson i think i have it working
