### ISSUE TITLE
layers not loading on mapper!

### ISSUE THREAD

**Issue by wetlandsDiane** [UGS-GIO/wetlands#47]
### What happened?

1.  I opened the mapper
2. I see a message that says "An error occurred loading this layer" under the Boundaries and Wetland Dependent Species parts of the Legend
3. I click on Landscape DAta, but no spatial data shows up
![image](https://user-images.githubusercontent.com/20359374/161098919-ac56140f-85a7-4eab-96a4-e3fb0c907a58.png)

### What did you expect to happen?

The layers to load and no error messages

### Browser Version

Chrome Version 99.0.4844.84 (Official Build) (64-bit)

**Comment by marthajensen** [comment]
It looks like the Server went down for a few minutes. Its back up now. Try to load the data again. You might need to refresh
