### ISSUE TITLE
add report link to Wetland Assessment Projects

### ISSUE THREAD

**Issue by wetlandsDiane** [UGS-GIO/wetlands#6]
The Bear wetland assessment project now has a report to be added under the Project Report tab. This is the link: https://geodata.geology.utah.gov/pages/view.php?ref=63232

**Comment by marshallrobinson** [comment]
Hey @marthajensen, the "Bear"-region feature in the Wetland Assessment Projects layer needs the url Diane mentioned added to the database.

**Comment by marthajensen** [comment]
The report link has been added to the data
