### ISSUE TITLE
This Application Needs a New Layer(s)

### ISSUE THREAD

**Issue by PeteGoodwinUGS** [UGS-GIO/wetlands#62]
### Why do you feel this application needs what you're requesting?

The LLWW data created as part of the Cache Valley mapping project has unique attributes that aren’t included in the NWI mapping data shown in the application. We created this LLWW data and would like to share it with potential data users.

### Describe the layer(s) you'd like to add

See document here:
https://docs.google.com/document/d/17Gx_FcjhixMulVJHwgAO0Nl1WIRDwYukebI6ba3XAWA/edit?usp=sharing

### Additional Context

Layer symbology can be found here:
"M:\Shared drives\UGS_Wetlands\Projects\CacheValley_LLWW\website update\Final LLWW Mapping.lyrx"

new layers to go here
![image](https://user-images.githubusercontent.com/69260042/211829521-aeddb8bf-8729-4b94-9601-69bc863e5ce9.png)
(not sure this added, let me know if it doesn't show up)

### Popup Formatting

see website update document here: 
https://docs.google.com/document/d/17Gx_FcjhixMulVJHwgAO0Nl1WIRDwYukebI6ba3XAWA/edit?usp=sharing

but
attributes and popups for LLWW Descriptions
**field name | alias to show in mapper**
cowattribute | Cowardin Attribute
featuretype | LLWW Feature Type
hgm_class | HGM Class
landscape | Landscape Position
landform_waterbody | Landform or Waterbody
flowpath | Flow Path
llww_base | LLWW Base Code
llww_modifiers | LLWW Modifiers

attributes and popups for LLWW Mapping Areas
**field name | alias to show in mapper**
projectname | Project Name
organization | mapping organization
baseimagery | Base Imagery
report | Supplemental Report

### Who has reviewed your database so far? (e.g. Schema, Field Types, Topology, etc.)

schema, fieldtypes, topology all reviewed by me as part of creating datapackage. Diane (@wetlandsDiane) provided cursory review of database contents and schema. Detailed review of database needs to be completed. 

### Who has reviewed your science and grammar so far for both your data and application panels?

initial text review by Diane (@wetlandsDiane)
Technical review needed from Stephanie (@geowomansteph)
1. Text to include in database contents
2. Document provided with data download with a more detailed description of dataset here:  
M:\Shared drives\UGS_Wetlands\Projects\CacheValley_LLWW\website update\2_LLWW_dataExplanation_PG6.docx
### Copy/paste all text for application panels here (e.g. About, Supplemental Data, Explanation)

Database Contents:

see 1_DatabaseContentsText_PG3 here:
M:\Shared drives\UGS_Wetlands\Projects\CacheValley_LLWW\website update

Document to provide with data download:
M:\Shared drives\UGS_Wetlands\Projects\CacheValley_LLWW\website update\2_LLWW_dataExplanation_PG6.docx

### Folder path of data

M:\Shared drives\UGS_Wetlands\Projects\CacheValley_LLWW\website update\FinalCacheMapping_website.gdb

**Comment by PeteGoodwinUGS** [comment]
Question about timing - how easy of an update is this and is feasible to have the update completed before Feb 14 to show at maps on the hill?  Thanks!

**Comment by marthajensen** [comment]
Hi Pete - we have at least one request ahead of yours, so we will do our best to get to it quickly. Steph Carney reviews only full sentences in databases. Do any of your columns have full sentences? If so, export out that data into a spreadsheet, and send it to Stephanie. I will review your data for all of the other attributes and make sure they are web-ready.

**Comment by geowomansteph** [comment]
I've completed my review and "signed off"

**Comment by PeteGoodwinUGS** [comment]
Updated GitHub ticket with links to revised documents

**Comment by marthajensen** [comment]
@jjhi11 

Nate and I published a service to ArcGIS Server for these 2 new layers

FinalFunctions_Calculated_ProjectArea (alias: LLWW Descriptions):(https://webmaps.geology.utah.gov/arcgis/rest/services/Wetlands/LLWW_Additional_Attributes/MapServer/0)https://webmaps.geology.utah.gov/arcgis/rest/services/Wetlands/LLWW_Additional_Attributes/MapServer/0

LLWW_Mapping_Areas (alias: LLWW Mapping Areas):
https://webmaps.geology.utah.gov/arcgis/rest/services/Wetlands/LLWW_Additional_Attributes/MapServer/1 

The popup and attribute table information for these 2 new layers, is highlighted in yellow, has been added to our Popupinfo sheet : https://docs.google.com/spreadsheets/d/1zDJkZQA3YGEFaqqUdxCgjwvkCI7GL2Y8FJVin9t-OPw/edit?usp=sharing

Pete would like the data to be downloaded and linked to the Database Contents pane. The downloadable zip file is at: \\geology.utah.gov\www\html\apps\wetlands\appfiles\LLWW Datasets.zip

Pete would also like some new text in the Database Contents. His new text is at the bottom of this document: https://docs.google.com/document/d/17Gx_FcjhixMulVJHwgAO0Nl1WIRDwYukebI6ba3XAWA/edit

**Comment by geowomansteph** [comment]
I looked at the last paragraph in the Doc and made a few suggestions.

steph

**Comment by PeteGoodwinUGS** [comment]
Thanks! Just revised the doc based on those suggestions

**Comment by PeteGoodwinUGS** [comment]
@jjhi11 
Just reviewed the review map and have these fixes:

1. Base imagery for the Cache Valley Mapping area should be NAIP 2016 not NAIP 2021. My fault when I typed in the data
![image](https://user-images.githubusercontent.com/69260042/217098502-cb3621b9-d402-4fd1-95a4-1eeb704e937a.png)
2. Popup for the LLWW Descriptions misspells Attribute
![image](https://user-images.githubusercontent.com/69260042/217098716-a07a32a1-69d8-49b5-ba0d-16c67c4b730a.png)
3. Clicking on the Cache Valley Supplemental report in the Database Contents window takes you to a "Redirect Notice" page and away from the web map. It would be nice if the supplemental report opened in another tab instead.
4. The LLWW dataExplanation file should be a pdf and should be renamed to "LLWW_dataExplanation"
5. c-133.pdf should be renamed to "Updated Wetland Mapping in Cache County_Circular133"
6. ofr-744.pdf should be renamed to "Cache Valley Supplemental Report"

**Comment by marshallrobinson** [comment]
- [ ] Increase/Decrease not affecting LLWW Descriptions layer
- [ ] Change "Additional Attributes" to "Additional Attributes (LLWW)"
- [ ] The hover text needs updated to reflect the new fields in LLWW Descriptions
- [ ] Landscape, Landform or Waterbody, Flowpath, and LLWW Modifiers fields need additional context to explain "TE" or "SL" etc. I suggest those fields read "Terrene (TE)", and "Slope (SL)"

**Comment by jjhi11** [comment]
@PeteGoodwinUGS 
Could you give me some text to add to the hover over each field in the popup please?  Example would be hovers over the wetlands data.

**Comment by PeteGoodwinUGS** [comment]
Hey Jay,

I would use these:

LLWW DESCRIPTORS
Cowardin Attribute = NWI Code
LLWW Feature Type = LLWW Feature Type
Landscape = Landscape Position
Landform or Waterbody = Wetland Landform or Waterbody Type
Flowpath = Water Flowpath
LLWW Base Code = LLWW Base Code
LLWW Modifiers = LLWW Modifiers

LLWW MAPPING AREAS
Project Name = Mapping Area
Organization = Mapped By
Base Imagery = Source Imagery and Date
Supplemental Report = Additional Information


Let me know if this doesn't work for you.

Thanks!
