### ISSUE TITLE
Remove Boundary features

### ISSUE THREAD

**Issue by wetlandsDiane** [UGS-GIO/wetlands#69]
### Name of Existing Layer (as it appears in the application)

River Sub basins and River basins

### Folder path of data

NA

### Why do you feel this application needs what you're requesting?

I would like to remove both layers in the Boundaries group from the application. I don't like having the boundaries cut off at the state border and the large basin names are distracting and in the way.

### Who has reviewed your database so far (e.g. Schema, Field Types, Topology, etc.)?

NA, removing a layer

### Who has reviewed your science and grammar so far?

NA

**Comment by wetlandsDiane** [comment]
We will also need to remove the Boudnaries information in the Data Contents panel

**Comment by marthajensen** [comment]
@jjhill This is a complete service on ArcGIS Server with only the river basins and the river sub basins -https://webmaps.geology.utah.gov/arcgis/rest/services/Wetlands/Boundaries/MapServer

Do you want me to delete the service entirely? Once you remove it from the web app?

**Comment by jjhi11** [comment]
@marthajensen Sure it can be deleted

**Comment by wetlandsDiane** [comment]
I think this issue can be closed
