### ISSUE TITLE
Suggest Static Text Edit to the About box- complete after updating the data

### ISSUE THREAD

**Issue by wetlandsDiane** [UGS-GIO/wetlands#74]
### Where is the text you are suggesting changes for?

About box

### What does the current text say?

This map contains data from NWI that is up-to-date as of June 21, 2023.

### What do you propose the new text says?

This map contains data from NWI that is up-to-date as of October 31, 2023.

**Please update the spatial data before updating the static text** 

### Who has reviewed your proposed text so far?

Only change is the date; no review needed.

**Comment by marshallrobinson** [comment]
Thanks Diane,

Agreed, no need for review. @jjhi11, please coordinate with @nmpayne so the date change comes after Nate makes the data update. @nmpayne, what is a reasonable timeframe to update the data in https://github.com/UGS-GIO/wetlands/issues/73

**Comment by nmpayne** [comment]
If there aren't any schema changes the process should be fairly straightforward. I'd say this week.

**Comment by nmpayne** [comment]
@wetlandsDiane The new data is uploaded and ready for your review.

**Comment by wetlandsDiane** [comment]
Hi Nate,

Can you add a new Decade to the legend under Wetland and Riparian Mapping/ Wetland Mapping/ Wetland Project Information? The decade will be 2020s. Not sure what color to make it. Can you select something on that or should I?

Thanks

**Comment by nmpayne** [comment]
@jjhi11 I think Jay will have to do that part.

**Comment by jjhi11** [comment]
done
