### ISSUE TITLE
Text edit to update database date

### ISSUE THREAD

**Issue by PeteGoodwinUGS** [UGS-GIO/wetlands#77]
### Where is the text you are suggesting changes for?

About box

### What does the current text say?

This map contains data from NWI that is up-to-date as of October 31, 2023.

### What do you propose the new text says?

This map contains data from NWI that is up-to-date as of June 5, 2024.

### Who has reviewed your proposed text so far?

No review needed since we're just updating the date in the above sentence.

**Comment by wetlandsDiane** [comment]
Should this issue be closed now?
