### ISSUE TITLE
BUG: database content downloads no longer working

### ISSUE THREAD

**Issue by wetlandsDiane** [UGS-GIO/wetlands#82]
### What happened?

1. Open database contents panel
2. Scroll down to Additional Attributes and LLWW Data
3. Select "download" (word in blue)
![image](https://github.com/user-attachments/assets/41d04c98-6bef-44b8-9eaa-c79376aeac25)
4. This is what I got!
![image](https://github.com/user-attachments/assets/e29fd6fa-090c-406c-891a-8a340175995a)
5. This issue is also a problem with the landscape and wetland assessment results:
![image](https://github.com/user-attachments/assets/449a265e-b2f8-42b7-a6b5-3945adb80cc5)

![image](https://github.com/user-attachments/assets/94ed10d9-3da2-4e98-930f-6ae5264f395e)

### What did you expect to happen?

I expect the correct datasets to download, likely as zip files

### Browser Version

Version 129.0.6668.70 (Official Build) (64-bit)

**Comment by marshallrobinson** [comment]
@clintonlunn, @nmpayne, @jjhi11 Perhaps this is related to Firebase?

**Comment by marshallrobinson** [comment]
closed by #84
