### ISSUE TITLE
Update date of data text on "Utah Wetlands" app

### ISSUE THREAD

**Issue by PeteGoodwinUGS** [UGS-GIO/wetlands#85]
### Where is the text you are suggesting changes for?

About box

### What does the current text say?

This map contains data from NWI that is up-to-date as of June 5, 2024. 

### What do you propose the new text says?

This map contains data from NWI that is up-to-date as of November 12, 2024. 

### Who has reviewed your proposed text so far?

Only changing the date; no review needed.

**Comment by geowomansteph** [comment]
Um, looks fine to me.  Please sign off for me.

**Comment by PeteGoodwinUGS** [comment]
Ok, thanks!

**Comment by nmpayne** [comment]
@jjhi11 This text is ready to be updated
